Worksheet-1(AI)

In [11]:
import numpy as np

Problem-1

In [ ]:
#4.1.
#1 Initialize an empty array with size 2X2.
a=np.empty((2,2))
a

array([[4.72512224e-315, 0.00000000e+000],
       [4.94065646e-324, 6.67021028e-310]])

In [ ]:
#4.2. Initialize an all one array with size 4X2.
a=np.ones((4,2))
a

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [ ]:
# 3. Return a new array of given shape and type, filled with fill value.{Hint: np.full}
a=np.full((2,2),fill_value=4,dtype=int)
a

array([[4, 4],
       [4, 4]])

In [ ]:
# 4. Return a new array of zeros with same shape and type as a given array.{Hint: np.zeros like}
a=np.zeros_like((a),dtype=float)
a

array([[0., 0.],
       [0., 0.]])

In [15]:
#5. Return a new array of ones with same shape and type as a given array.{Hint: np.ones like}
arr7=np.array([[1,2],[3,4]])
b=np.ones_like(arr7,dtype=float)
b

array([[1., 1.],
       [1., 1.]])

In [ ]:
#6.For an existing list new_list = [1,2,3,4] convert to an numpy array.{Hint: np.array()}
new_list=[1,2,3,4]
a=np.array(new_list)
a

array([1, 2, 3, 4])

Problem-2

In [ ]:

# 1. Create an array with values ranging from 10 to 49. {Hint:np.arrange()}.


ar1= np.arange(10, 50).reshape(8, 5)
ar1


array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

In [ ]:
# 2. Create a 3X3 matrix with values ranging from 0 to 8.

arr2 = np.arange(0, 9).reshape(3, 3)
arr2


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
# 3. Create a 3X3 identity matrix.{Hint:np.eye()}
arr3=np.eye(3)
arr3

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
# 4. Create a random array of size 30 and find the mean of the array.
arr3=np.random.random(30)
mean_v=arr3.mean()
arr3,mean_v



(array([0.13967506, 0.80267788, 0.85148532, 0.71625698, 0.91223892,
        0.35486758, 0.41443544, 0.40830571, 0.16209805, 0.92240495,
        0.52605049, 0.37626056, 0.02777293, 0.13049897, 0.96158615,
        0.25271624, 0.94297051, 0.52917296, 0.91033163, 0.5532868 ,
        0.78025033, 0.13835719, 0.02003922, 0.00249648, 0.85407817,
        0.90253985, 0.72287828, 0.06595955, 0.56795024, 0.69991661]),
 np.float64(0.5216519677067779))

In [ ]:
# 5. Create a 10X10 array with random values and find the minimum and maximum values.
arr4=np.random.random(10)
mean_v=arr4.min()
max_v=arr4.max()
arr4,mean_v,max_v

(array([0.5955038 , 0.45015052, 0.81648384, 0.73557499, 0.97652493,
        0.79062336, 0.3198179 , 0.00488591, 0.30227721, 0.97181257]),
 np.float64(0.004885909543695943),
 np.float64(0.9765249278306545))

In [ ]:
# 6. Create a zero array of size 10 and replace 5th element with 1.
arr4=np.zeros(10)
arr4[5]=1
arr4

array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0.])

In [16]:
# 7. Reverse an array arr = [1,2,0,0,4,0].
arr=np.array([1,2,0,0,4,0])
reverse_ar=list(reversed(arr))
reverse_ar



[np.int64(0), np.int64(4), np.int64(0), np.int64(0), np.int64(2), np.int64(1)]

In [17]:
#8. Create a 2d array with 1 on border and 0 inside.
arr6=np.ones((3,3))
arr6[1,1]=0
arr6

array([[1., 1., 1.],
       [1., 0., 1.],
       [1., 1., 1.]])

In [18]:
#9.Create a 8X8 matrix and fill it with a checkerboard pattern.


arr9=np.zeros((8,8))
for i in range(8):
  for j in range(8):
    if (i+j)%2== 1:
       arr9[i,j] = 1
arr9

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

Problem-3

In [51]:
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])

print("Addition is:",x+y,v-w)
print("Subtraction is:",x-y,v-w)
print("Multiplication is:",x*y,v*w)
print("Square is:",x**2,y**2,v**2,w**2)

#dot prodct
print("Dot product bet x and v:",np.dot(x,v))
print("Dot product bet v and w:",np.dot(v,w))
print("Dot product bet x and y:",np.dot(x,y))

#concatenate
print("Concat x and y row:",np.concatenate((x,y),axis=0))
print("Concat v and w column:",np.concatenate((v,w),axis=0))

print("Concat betn x and v")
try:
    print(np.concatenate((x,v)))
except ValueError as e:
    print("Error:",e)



Addition is: [[ 6  8]
 [10 13]] [-2 -2]
Subtraction is: [[-4 -4]
 [-4 -3]] [-2 -2]
Multiplication is: [[ 5 12]
 [21 40]] [ 99 120]
Square is: [[ 1  4]
 [ 9 25]] [[25 36]
 [49 64]] [ 81 100] [121 144]
Dot product bet x and v: [29 77]
Dot product bet v and w: 219
Dot product bet x and y: [[19 22]
 [50 58]]
Concat x and y row: [[1 2]
 [3 5]
 [5 6]
 [7 8]]
Concat v and w column: [ 9 10 11 12]
Concat betn x and v
Error all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)


Problem-4

In [54]:
import numpy as np

A=np.array([[3,4],[7,8]])
B=np.array([[5,3],[2,1]])

A_inv= np.linalg.inv(A)
result1=np.dot(A,A_inv)
print("A.A−1 = I: ",np.allclose( result1,np.eye(2)))
AB= np.dot(A, B)
BA=np.dot( B,A)
print("AB ≠ BA:",not np.array_equal(AB,BA))

AB_T =AB.T
BT_AT =np.dot (B.T, A.T)
print ("(AB)T = BT AT: ",np.array_equal( AB_T,BT_AT))
A_eq=np.array([[2,-3,1],[1,-1,2],[3,1,-1]])
B_eq=np.array([-1,-3,9])
solution =np.linalg.solve (A_eq,B_eq)
print("Solution is:", solution)

A.A−1 = I:  True
AB ≠ BA: True
(AB)T = BT AT:  True
Solution is: [ 2.  1. -2.]


Problem-4.2

In [56]:
import time
#size
n =1000000
m= 100

a= list(range(n))
b= list(range(n,2*n))
x =np.arange(n)
y =np.arange(n,2*n)
print("addition of two lists:")

t1=time.time()
c = [a[i]+b[i] for i in range(n)]
t2=time.time()
print("using Python:",t2-t1)

t1=time.time()
z = x+y
t2=time.time()
print("using Numpy:",t2-t1)

print("Multiplication of lists:")
t1=time.time()
c=[a[i]*b[i] for i in range(n)]
t2=time.time()
print("using Python:",t2-t1)

t1=time.time()
z =x*y
t2=time.time()
print("using Numpy:",t2-t1)


print("dot product:")
t1=time.time()
p = sum([a[i]*b[i] for i in range(n)])
t2=time.time()
print("using Python:",t2-t1)
t1=time.time()
q = np.dot(x,y)
t2=time.time()
print("Numpy:",t2-t1)


print("Multiplication of matrix:")
matA= [[i+j for j in range(m)] for i in range(m)]
matB= [[i-j for j in range(m)] for i in range(m)]

t1=time.time()
matC = [[0]*m for _ in range(m)]
for i in range(m):
 for j in range(m):
   for k in range(m):
     matC[i][j]+=matA[i][k]*matB[k][j]
t2=time.time()
print("Time using Python:",t2-t1)

npA=np.array(matA)
npB=np.array(matB)
t1=time.time()
npC=np.dot(npA,npB)
t2=time.time()
print("Time using Numpy:",t2-t1)

addition of two lists:
using Python: 0.07326698303222656
using Numpy: 0.0027382373809814453
Multiplication of lists:
using Python: 0.07580733299255371
using Numpy: 0.0013148784637451172
dot product:
using Python: 0.08925104141235352
Numpy: 0.002015352249145508
Multiplication of matrix:
Time using Python: 0.1745305061340332
Time using Numpy: 0.0008559226989746094
